### PR TITLE
Update to version 0.1.14

### PR DESCRIPTION
**Pull request by xl0**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xl0** [comment]
@sugatoray , please have a look.

> I also removed the dependencies that are covered by lovely-numpy. Is it the correct practice?

Hi @xl0 ,

Sorry, for a late response. Yes, the dependencies of any dependency can be removed. But, normally what we keep here is at least the same set of dependencies as `install_requires` in setup.py of the upstream repo (`lovely_tensor`). Please check that you remove dependencies of `lovely_numpy` there as well.

**Comment by xl0** [comment]
@sugatoray , ping

**Comment by xl0** [comment]
@sugatoray, I think you misclicked and edited my reply instead of replying, so I never saw your reply.

Yep, I'm removing the redundant dependencies upstream too.

**Comment by sugatoray** [comment]
> @sugatoray, I think you misclicked and edited my reply instead of replying, so I never saw your reply.
> 
> Yep, I'm removing the redundant dependencies upstream too.

Sorry, if I did that. :D
Let me go ahead and merge this one now.

**Comment by sugatoray** [comment]
@xl0 I didn't see you running `@conda-forge-admin, please rerender` in any of the comments.
Please make sure that you always run it. This was mentioned in the PR description.

@conda-forge-admin, please rerender

**Comment by sugatoray** [comment]
@conda-forge-admin, please rerender

**Comment by sugatoray** [comment]
Closes #2

**Pull request merged**
